package com.me;

/**
 * Created by Babbaj on 4/25/2018.
 */
public interface Weapons {

    String[] NAMES = {
            "unarmed",
            "energy_sword",
            "energy_sword_hilt",
            "gravity_hammer",
            "flag",
            "oddball",
            "assault_bomb",
            "mauler",
            "mauler_pwr",
            "magnum",
            "magnum_dmg",
            "magnum_pwr",
            "needler",
            "plasma_pistol",
            "plasma_pistol_pwr",
            "assault_rifle",
            "assault_rifle_dmg",
            "assault_rifle_acc",
            "assault_rifle_rof",
            "assault_rifle_pwr",
            "battle_rifle",
            "battle_rifle_amm",
            "battle_rifle_dmg",
            "battle_rifle_acc",
            "battle_rifle_rof",
            "battle_rifle_rng",
            "battle_rifle_pwr",
            "beam_rifle",
            "covenant_carbine",
            "covenant_carbine_amm",
            "covenant_carbine_dmg",
            "covenant_carbine_acc",
            "covenant_carbine_rof",
            "covenant_carbine_rng",
            "covenant_carbine_pwr",
            "dmr",
            "dmr_amm",
            "dmr_dmg",
            "dmr_acc",
            "dmr_rof",
            "dmr_pwr",
            "plasma_rifle",
            "plasma_rifle_pwr",
            "shotgun",
            "smg",
            "smg_dmg",
            "smg_acc",
            "smg_rof",
            "smg_pwr",
            "sniper_rifle",
            "spike_rifle",
            "flak_cannon",
            "rocket_launcher",
            "spartan_laser",
            "brute_shot",
            "sentinel_gun"
    };
}
